/************************************************************\
 **     Copyright (c) 2012-2023 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	E:/FPGA_work/Anlogic/An1_020/fifo_ov5640_lcd480/al_ip/video_fifo.v
 ** Date	:	2023 07 09
 ** TD version	:	5.6.71036
\************************************************************/

`timescale 1ns / 1ps

module video_fifo (
	rst,
	di, clkw, we,
	do, clkr, re,
	empty_flag,
	full_flag 
);

	input rst;
	input [15:0] di;
	input clkw, we;
	input clkr,re;

	output [15:0] do;
	output empty_flag;
	output full_flag;

EG_LOGIC_FIFO #(
 	.DATA_WIDTH_W(16),
	.DATA_WIDTH_R(16),
	.DATA_DEPTH_W(4096),
	.DATA_DEPTH_R(4096),
	.ENDIAN("BIG"),
	.RESETMODE("SYNC"),
	.E(0),
	.F(4096),
	.ASYNC_RESET_RELEASE("SYNC"))
fifo_inst(
	.rst(rst),
	.di(di),
	.clkw(clkw),
	.we(we),
	.csw(3'b111),
	.do(do),
	.clkr(clkr),
	.re(re),
	.csr(3'b111),
	.ore(1'b0),
	.empty_flag(empty_flag),
	.aempty_flag(),
	.full_flag(full_flag),
	.afull_flag()

);

endmodule